### ISSUE TITLE
$ signs for totals

### ISSUE THREAD

**Issue by lucakato** [closup/process-xbrl#121]
**current view (business activities set to Y), using this attached template:**
[ACFR_template_sarrah-10-07-24.axlsx.xlsx](https://github.com/user-attachments/files/17479692/ACFR_template_sarrah-10-07-24.axlsx.xlsx)

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/b81a4f4c-4f20-4e84-ac26-d122887bceb5">
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/8a2de105-a2ec-4baf-bb66-ed8496a88014">
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/91ee2c51-5801-48a3-b505-6b27e383ddeb">

@sarraha786 could you update the template so that it has $ for all totals. And also check if examples show $ for sub-totals too?
once I have the updated one I can see if there's any code things that need to be updated too.

Thanks

**Comment by sarraha786** [comment]
Completed this. every field should automatically have a $ now.
[ACFR_template.xlsx](https://github.com/user-attachments/files/17481788/ACFR_template.xlsx)

**Comment by lucakato** [comment]
> Completed this. every field should automatically have a $ now. [ACFR_template.xlsx](https://github.com/user-attachments/files/17481788/ACFR_template.xlsx)

Thanks

**Comment by lucakato** [comment]
@sarraha786 Please let me know once your testing is done and if there's any changes I need to make before emailing Ram.
One thing I do wanna see is if the $ is not showing for sub-totals/totals because maybe it's a code issue. You can test a template against the Heroku app.
