### ISSUE TITLE
Template Conditions

### ISSUE THREAD

**Issue by sarraha786** [closup/process-xbrl#122]
-  If Business Type Activities = N in mastersheet info: Business type activity columns and total primary govt columns will disappear on Statement of net position and Statement of Activities. Also, ideally, prop fund statements disappear.

- If Governmental Actitivities=N in mastersheet info: all govt columns and primary govt columns disappear. Ideally, only the 3 propfund statements remain.

- If both of these conditions are set to yes, the template should appear with all columns and statements as default.

**Comment by lucakato** [comment]
made changes in branch #122-bs-actv-N

New Code:
```python
# Check if column has any non-empty evaluated values
has_values = False
for value in column_data:
    if pd.notna(value) and str(value).strip() != "":
        has_values = True
        break
```
The differences in handling:
**Empty String Cases:**
```
Old: Would keep a column if it had empty strings ("") because they're not NaN
New: Will drop a column if it only contains empty strings or whitespace
```
**Formula Cases:**
```
Old: Would keep a column if formulas existed, even if they evaluated to empty/blank
New: Only keeps the column if at least one formula evaluates to a non-empty value
```
Specific Examples:
```
Column A    | Column B              | Column C
"data"      | =IF(A1="","",A1)     | =IF(D1="","",SUM(D1:D10))
""         | ""                    | ""
""         | =IF(A3="","",A3)     | ""
```
Old code would keep all three columns
New code would:
- Keep Column A (has actual data)
- Keep Column B (formula evaluates to "data")
- Drop Column C (all values evaluate to empty)

**Hidden Excel Cells:**
Old: Might keep columns with hidden cells containing formulas
New: Only keeps columns if they have actual visible/non-empty values
