### ISSUE TITLE
Hide secret key

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#128]
If we plan to keep the code open source, we need to hide the Flask secret key: https://github.com/closup/process-xbrl/blob/607bc4db99b88dc692519f7fab4d9ee45b1fe865/app/.env#L1

This should go into a json file inside a `.secret` folder.

**Comment by lucakato** [comment]
Looks like I forgot to add `.env` to the `.gitignore` file. This would have made sure it never got pushed. That's why I made it load from env file

**Comment by lucakato** [comment]
merged to dev, done.
