### ISSUE TITLE
Formatting issues with the dev branch

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#129]
@lucakato Documenting here what we've emailed about. 

## Ogemaw template issue

This issue might be because the template has been updated but Ogemaw's template hasn't?

<img width="1066" alt="Screenshot 2024-11-11 at 1 35 13 PM" src="https://github.com/user-attachments/assets/c5c5a977-5173-4af0-9cf5-4386a924a0c4">

Generated using 
[updated_ACFR_Ogemaw_template.xlsx](https://github.com/user-attachments/files/17801131/updated_ACFR_Ogemaw_template.3.xlsx) a

## Clayton issues

Header/subheader rows don't show up or get color-coded correctly

Dev branch Clayton:
![Screenshot 2024-11-18 at 12 38 30 PM](https://github.com/user-attachments/assets/79d800f5-c729-4e1b-babd-d83148d74b05)

Expected (output using code on main branch):
![Screenshot 2024-11-18 at 12 38 42 PM](https://github.com/user-attachments/assets/973cd2d0-7886-41ac-b76f-367ca73a305a)

**Comment by lucakato** [comment]
@kwheelan I've addressed this, merged to dev. perhaps a double check may be good tho.

**Comment by kwheelan** [comment]
@lucakato Looks good!
