### ISSUE TITLE
Revert treatment of reconciliation tables

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#131]
The taxonomy doesn't have tags for cells in the reconciliation tables, so they should not be "clickable" or treated as tagged cells.

Right now on `dev`, reconciliation tables are getting incorrectly ID'ed as xbrl elements with empty concept and dimensions. The dev branch output from Clayton:
![Screenshot 2024-11-18 at 12 44 59 PM](https://github.com/user-attachments/assets/1160a35f-1856-4e2b-b654-e3fbdab3ca40)

Expected behavior when you click "highlight XBRL elements on the viewer" (ie. no highlighting and unclickable cells): 
![Screenshot 2024-11-18 at 12 45 49 PM](https://github.com/user-attachments/assets/01a7e47e-c855-4a9d-8d1f-c0d4fa959b51)

**Comment by lucakato** [comment]
@kwheelan I've addressed this, merged to dev

**Comment by kwheelan** [comment]
Closing issue
