### ISSUE TITLE
OPEB line item being highlighted / shadow

### ISSUE THREAD

**Issue by lucakato** [closup/process-xbrl#141]
**How to replicate:**
- Test this file provided by Ram: 
[Lakewood City School District.xlsx](https://github.com/user-attachments/files/17927725/Lakewood.City.School.District.xlsx)

**Issue:**
The OPEB line item should not be highlighted
![image](https://github.com/user-attachments/assets/7022779b-9a64-4461-9bef-ce9a76bda901)
![image](https://github.com/user-attachments/assets/fe80a5c2-1939-42b1-921b-b48a82d1c20d)

**Comment by lucakato** [comment]
@kwheelan couldn't figure out how the axes worked so I added this condition and it works:
![image](https://github.com/user-attachments/assets/8d3273f9-7254-4733-8ea9-cf4ab4f2c79a)

**Comment by kwheelan** [comment]
@lucakato That works, but in service of avoiding hard-coding, I recommend that you change it to something like `self._row_name.strip() not in HEADER_EXCEPTIONS` And define `HEADER_EXCEPTIONS` in `app/utils/constants.py`

**Comment by lucakato** [comment]
@kwheelan makes sense, just changed and merged
