### ISSUE TITLE
improve file uploads

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#37]
## Goal 

Improve the process for uploading files on the app. We want to allow the user to upload files from multiple folders (right now they must all be in the same folder). We can either allow multiple upload rounds or allow the user to select files from different folders in the dialog box.

## Background

- `app/templates/site/home.html` includes the html code for the file upload form (lines 22-40)
- `app/static/js/spinner.js` is badly named, but it contains all the javascript code that controls the draggable file list (and that submits the POST request).
- The `upload_files()` function in `routes.py` processes the POST request and receives the `files[]` array

**Comment by lucakato** [comment]
@kwheelan I don't think it's possible to select multiple folders according to [this](https://stackoverflow.com/questions/49530674/input-type-file-directory-multiple). Instead, it might make sense to add a delete button next to each file. This way if the user accidentally uploads 1 extra file they don't have to go through the re-selection process of all files again, but just delete the single file.

**Comment by kwheelan** [comment]
@lucakato That makes sense -- we'll just have to make sure the file request still includes all the files in the correct order.

**Comment by lucakato** [comment]
@kwheelan Should be done but please check whenever. I also changed the saving location of viewer.html to templates/site because I realized saving it to sessions specific folder was deleting it.

**Comment by kwheelan** [comment]
@lucakato Thanks -- I'll take a look this weekend.

**Comment by kwheelan** [comment]
@lucakato 

Thanks for your work on this. A few comments:

- Re moving the location of viewer.html: we ultimately need that file to be written to a session-specific file. If we write to `templates/` one person using the app will change the viewer for all users. Writing to a session-specific file should allow multiple simultaneous users. What error were you getting? We might just need to move the javascript it relies on to a different location. I haven't looked closely at the actual script, but if it's different for each viewer instances, we'll need to move it into the sessions folders as well. See lines 78-88 of `app/utils/xbrl_processing.py` where we move the js script and change the reference in the viewer html. 

- I like the delete button, but the update on the number of files displayed on the message "Convert X files" is not always accurate. When I add 5 files and delete some, it doesn't always correctly decrease the file count. We can probably just get rid of the counter completely and have it say "convert your files." But it seems like there is something else going on because I've also had some other unexpected behavior when testing. When I upload several files and delete all but the Excel file, I get the error "please upload exactly 1 Excel file."

- I'll do a bit of research as well to see if we can find a way to get file uploads from multiple locations to work. I'll leave this issue open until then.

**Comment by lucakato** [comment]
@kwheelan thanks for the review. I'll try to re-create that error I got by reverting it to saving to the session specific folder.

I'll also just keep it to 'Convert X files' and then test it more.

**Comment by kwheelan** [comment]
@lucakato Let me know if/when you want me to review this

**Comment by lucakato** [comment]
@kwheelan thanks. I fixed the error message thing. I was working on this other bug where files weren't being shown when everything was deleted and then files were re-selected to be uploaded but now that's been fixed too.
Then I'll probably try moving the saving location of viewer.html back to the session and see if I break anything again.

**Comment by kwheelan** [comment]
@lucakato Sounds good

**Comment by lucakato** [comment]
@kwheelan okay so here's the error message:
<img width="1033" alt="image" src="https://github.com/closup/process-xbrl/assets/55814205/e28c30ad-b1b4-46ec-84e4-9de7b1e90ee8">
I think render_template only works on something stored in the /templates folder.

Do you think modifying the folder/code structure like this is okay?
`
project_root/
    app/
        templates/
            session_templates/
                sessions_data/
                    <session_id>/
                        viewer.html
            base.html
            other_template.html
        static/
            css/
            js/
        routes.py
        ...
`

**Comment by kwheelan** [comment]
@lucakato 

I would advocate for keeping all the session-specific data in one folder inside `static`.

I think you should be able to fix your errors by resetting the default location for templates. Try editing [line 16 in routes.py](https://github.com/closup/process-xbrl/blob/main/app/routes.py#L16) to be something like this:
```
current_directory = os.path.dirname(os.path.abspath(__file__))
routes_bp = Blueprint('routes_bp', __name__, template_folder=current_directory)
```
Then you would just have to edit the other filepaths in `render_template()` to be something like `render_template("templates/site/upload.html")` instead of `render_template("site/upload.html")`. For the output files you should then be able to  do `render_template(f'static/sessions-data/{session_id}/output/viewer.html')`.

**Comment by kwheelan** [comment]
@lucakato It looks like that screenshot might be a conversion from part of a word doc we didn't convert in the demo. I think that one of the Word docs contains most of the ACFR (including content that should instead be in the Excel). Try with the two attached word docs and let me know if you still have any odd formatting issues.
[Clayton_Cover_Page_and_Intro.docx](https://github.com/user-attachments/files/16134310/Clayton_Cover_Page_and_Intro.docx)
[Sample Note w Comments.docx](https://github.com/user-attachments/files/16134311/Sample.Note.w.Comments.docx)

**Comment by kwheelan** [comment]
Re: saving the images in `session_id/input` I think that makes sense. It should also be easier for clearing unneeded data after the session ends since you can just delete the one session folder.

**Comment by lucakato** [comment]
@kwheelan No formatting issues with those 2 docs + Clayton.xlsx!
