### ISSUE TITLE
Template Notes from Marc - 5/3/2024

### ISSUE THREAD

**Issue by joffemd** [closup/process-xbrl#39]
I found some issues and am making changes to the workbook.  I think I will send you a revised workbook including not only the Clayton data but formula and name changes as well.

Some formulas under Total Primary Government are missing
Noncurrent Assets Dropdown is Wrong; Its Showing Deferred Outflows
The XLOOKUP Net Position range should be extended to cell 608. It is ending at 514 now.

On the Governmental Funds Balance Sheet, the validation ranges sometimes contain blanks because we don't have matching modified accrual elements for each full accrual element.  We're going to have to maintain separate lists on separate worksheets.

PropFund Stmt of Rev Exp and Ch - This doesn't seem like we got the tags from the right part of the taxonomy.  This sheet will have to be reworked to support Clayton only for now.

On Statement of Activities, we have a spec challange.  Within General Revenues, the Clayton ACFR has a subtotal called "Total Taxes".  If I include that, the grand total would include a lot of double counting.  I have left it blank for now, so that we can tie out.

**Comment by kwheelan** [comment]
> On the Governmental Funds Balance Sheet, the validation ranges sometimes contain blanks because we don't have matching modified accrual elements for each full accrual element. We're going to have to maintain separate lists on separate worksheets.

@joffemd FYI this is something Sarrah is fixing in #36 

Generally, are you planning to make all these changes yourself or are these edits you want us to implement?

**Comment by joffemd** [comment]
I just made a whole bunch of changes to get Clayton 2022 close to working.  At this point, I suggest that you and Sarrah use my update as a base and keep the Clayton data in.
________________________________
