### ISSUE TITLE
Add back button

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#52]
## Goal

Add a button to the `/upload/complete` page to let the user go back home (to the template download/ file upload page).

## Background

- This should be a relatively quick fix in `app/templates/site/upload.html`, but you may want to change `base_page.html` and/or the CSS in `app/static/css/style.css`)

**Comment by lucakato** [comment]
@kwheelan pushed to branch #52-add-back-button pls check.

**Comment by kwheelan** [comment]
@lucakato Lmk when you push the button text change (or tag #52 in the commit message) and I'll merge -- thanks

**Comment by lucakato** [comment]
@kwheelan just did thanks. I'll also try to do the download jinja thing by today.
