### ISSUE TITLE
download from session_id folder to user's downloads

### ISSUE THREAD

**Issue by lucakato** [closup/process-xbrl#58]
Goal: Be able to download output.html (now stored under a specific session folder) once conversion is complete.

This line defines the download:

<img width="940" alt="image" src="https://github.com/closup/process-xbrl/assets/55814205/0266b450-d66c-46d3-8a11-ff9ed9c2c6c6">

The download="converted_xbrl.html" means that when you download the file, it will be called converted_xbrl.html, but the first attribute (href) actually provides the document to be downloaded. Right now, it's set to static/output/output.html, but we'll want to change that to the session-specific file (saved in `static/sessions_data/<session-id>/output/output.html`).

You can definitely do this with javascript if you prefer, but it might be easier to do it with jinja2 formatting. If you go with the jinja2 route, you'll want to pass the session id to the render_template() function here:

<img width="934" alt="image" src="https://github.com/closup/process-xbrl/assets/55814205/55fb24f1-710a-428f-b53a-b810dace2abf">

and then adjust the `href` in the download anchor in [upload.html](https://github.com/closup/process-xbrl/blob/1b0813f51e63872b998e04a6fe0997632d9a20bc/app/templates/site/upload.html#L11)

**Comment by lucakato** [comment]
@kwheelan Could you check out branch #58-downloads-session-id (I made this code based on branch #52) and see if it works for you? I'm getting the following error I'm wondering if it's the merge conflicts you resolved. Tested it on just Clayton.xlsx

<img width="692" alt="image" src="https://github.com/closup/process-xbrl/assets/55814205/66054ec5-2723-4c49-ab31-2edadf203f3c">

<img width="679" alt="image" src="https://github.com/closup/process-xbrl/assets/55814205/b6e4d9cb-be3a-488a-81c6-358e0b6204cd">

**Comment by kwheelan** [comment]
@lucakato I'm traveling today, but I'll fix the merge issues by the evening.

**Comment by lucakato** [comment]
@kwheelan no worries, I'll also have a look. thanks

**Comment by kwheelan** [comment]
@lucakato All the merge issues should be fixed. I've merged this into the `dev` branch. Is this issue ready to close or do you need to add changes to the file save locations on this branch?

**Comment by kwheelan** [comment]
Hmm it is working for me, but what document are you uploading? Try this one, and let me know if you still get errors.
[Clayton Excel.xlsx](https://github.com/closup/process-xbrl/files/15421501/Clayton.Excel.xlsx)

**Comment by kwheelan** [comment]
@lucakato Aha yes that one is old. It must have an issue somewhere in the Excel sheet

**Comment by lucakato** [comment]
@kwheelan yup It works. Regarding the viewer, do you want viewer.html to be saved in `site/`? or under the session folder
<img width="655" alt="image" src="https://github.com/closup/process-xbrl/assets/55814205/95f16d67-f978-483b-af63-85aa331697c2">

**Comment by kwheelan** [comment]
@lucakato It should be saved under the user's sessions folder. If that breaks anything major, lmk and we can try to troubleshoot.

**Comment by lucakato** [comment]
@kwheelan just made that change!
