### ISSUE TITLE
Improve web design

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#6]
## Goal:

Make the site look more professional and generally better looking...

## Info:

The relevant html code for the web app is in `template/site/`. `base_page.html` will be the more important document to change. The associated CSS document is in `static/css/style.css`. The html pages use [jinja2](https://palletsprojects.com/p/jinja/) formatting.

**Comment by nfitz1** [comment]
UM/CLOSUP Branding information:

1. UM Official Colors: https://brand.umich.edu/design-resources/colors/
2. Possible CLOSUP logo to use: https://mpps.umich.edu/mpps-header.gif OR https://closup.umich.edu/sites/closup/files/closup-signature-informal-web.png

**Comment by nfitz1** [comment]
Update: Looks like we can get acfr.closup.fordschool.umich.edu; Natalie is also exploring embedding the heroku site on a page on the CLOSUP website, let's discuss on 4/9/24

**Comment by kwheelan** [comment]
Implemented on https://closup.umich.edu/acfr-tool
