### ISSUE TITLE
Move app to AWS

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#63]
- [ ] Move app to UM AWS servers before the end of June
 - [ ] Cancel Heroku
 - [ ] Possibly change URL

**Comment by lucakato** [comment]
@nfitz1 Hi Natalie, are there any things U-M specific things that I need to know to attempt this? I've done a bit of AWS so would like to learn/try it out.

**Comment by nfitz1** [comment]
Thanks Luca.  This move is most likely on hold for a little bit, I think we're going to be able to stick with Heroku for a little while longer, but I will absolutely loop you in when we are ready to start, so thanks for letting me know you're interested!

**Comment by lucakato** [comment]
Sounds good thanks

**Comment by nfitz1** [comment]
New CLOSUP Heroku account created, and app transfered on 6/21/24, this issue should be considered on-hold until further notice

**Comment by kwheelan** [comment]
I'm closing this issue for now. It can be re-opened when the web team has the managed AWS environment ready for us to move the app over.
