### ISSUE TITLE
Improve web design

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#68]

**Comment by lucakato** [comment]
@nfitz how strict are we on colors? right now it's maize & blue but are we open to modifying some colors or do we want to stay with this color theme?

**Comment by nfitz1** [comment]
I'd like to stick with maize & blue as the primary color scheme. If you
need additional colors, try the "secondary palette" on
https://brand.umich.edu/design-resources/colors/

-Natalie
-------------
Natalie Fitzpatrick
Project Manager
Center for Local, State, and Urban Policy (CLOSUP)
University of Michigan Gerald R. Ford School of Public Policy
735 S. State Street, #5312
Ann Arbor, MI  48109-3091

http://closup.umich.edu/
