### ISSUE TITLE
Add capacity for footnotes in tables

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#69]
- [x] Look through ACFRs to see if there are any examples of footnotes in the tables instead of notes at the end of the ACFR (maybe in New Jersey?)
 - [x] If they exist, we'll need to add a space in the template for the notes 
 - [ ] And capacity in the conversion code/ jinja template for the footnotes

**Comment by nfitz1** [comment]
I found one example on page 22 of https://www.cliftonnj.org/ArchiveCenter/ViewFile/Item/174 ; it's not in one of the core statements but at least is an example of what it might look like!

**Comment by sarraha786** [comment]
[ACFR_template.xlsx](https://github.com/user-attachments/files/17063712/ACFR_template.xlsx)

**Comment by lucakato** [comment]
> [ACFR_template.xlsx](https://github.com/user-attachments/files/17063712/ACFR_template.xlsx)

this showed up in:
- Governmental Funds
Reconciliation Of Governmental Funds Balance Sheet To The Statement Of Net Position
AND
- Governmental Funds
Reconciliation Of Governmental Funds Statement Of Revenues, Expenditures, And Changes In Fund Balances To The Statement Of Activities And Changes In Net Position

**Comment by lucakato** [comment]
> [ACFR_template.xlsx](https://github.com/user-attachments/files/17063807/ACFR_template.xlsx)

works when shifted.

**Comment by sarraha786** [comment]
[ACFR_template.xlsx](https://github.com/user-attachments/files/17064127/ACFR_template.xlsx)

Updated template with footnotes corrected.

**Comment by sarraha786** [comment]
The most recent version of the template now includes an option to include or exclude footnotes in the Master Info sheet. 
[ACFR_template.xlsx](https://github.com/user-attachments/files/18084783/ACFR_template.xlsx)
