### ISSUE TITLE
Fix JS code for spinner

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#81]
# Error

<img width="1440" alt="Screen Shot 2024-07-19 at 7 57 17 PM" src="https://github.com/user-attachments/assets/05d5fb0c-d741-449f-a9d2-af73196c9b70">

## Text

```
Uncaught TypeError: Cannot read properties of undefined (reading 'preventDefault')
    at startProcessing (spinner.js:160:11)
    at HTMLInputElement.onclick ((index):61:137)
```

**Comment by lucakato** [comment]
fixed in branch 82-fix-viewer-js
