### ISSUE TITLE
Fix location and script tag for ixbrlviewer.js

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#82]
## Error

The interactive viewer isn't working correctly because it does not recognize the file path to the javascript file that makes it interactive. The unrecognized script tag is in `viewer.html`.

<img width="1438" alt="Screen Shot 2024-07-19 at 7 14 43 PM" src="https://github.com/user-attachments/assets/bf3ac88d-a5f4-4ba8-bd0c-e21128fd1d4f">

## Text in JS console

```
ixbrlviewer.js')%20%7D%7D:1 
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
```

## Text in Flask/Python log

```
127.0.0.1 - - [22/Jul/2024 15:09:18] "GET /{{%20url_for('static',%20filename='js/ixbrlviewer.js')%20}} HTTP/1.1" 404 -
```

## Thoughts

 - I'm not sure if the js changes each time it renders the viewer (depending on the data). We'll need to check this, because if the script does depend on the data, we'll need to move it into the session-specific folder. 
 - It also looks like the html isn't correctly parsing the jinja2 templating to get the file path. We may have to replace that line with an absolute file path to the script.

**Comment by kwheelan** [comment]
@lucakato Could you look into this? Happy to help if you get stuck

**Comment by lucakato** [comment]
@kwheelan will do thank you.

**Comment by lucakato** [comment]
@kwheelan hard-coding it removed the error but I may look into alternatives.

**Comment by lucakato** [comment]
@kwheelan A separate question but do you remember if there were supposed to be `output.html` which is different from `viewer.html`?

I was looking at the following in xbrl_processing.py and noticed how `output_file` is same as `viewer_filepath` when defining this `args` variable. I forgot if I changed something (I may have named every html that's produced as viewer.html instead of output.html). It's not causing errors but I want to make sure I understand what's happening especially in the line

```Python
args = f"--plugins={plugins} -f {output_file} --save-viewer {viewer_filepath} --viewer-url {viewer_url}"
args = shlex.split(args)
```

```Python
def create_viewer_html(output_file : str,
                       viewer_outpath : str):
    """
    Runs Arelle and ixbrl-viewer submodules to create a viewer html and 
    accompanying javascript file.
    """
    viewer_filepath = os.path.join(ROOT, viewer_outpath, 'viewer.html')

    # command to run Arelle process
    plugins = os.path.join(ROOT, "dependencies", "ixbrl-viewer", "iXBRLViewerPlugin")
    viewer_url = "https://cdn.jsdelivr.net/npm/ixbrl-viewer@1.4.8/iXBRLViewerPlugin/viewer/dist/ixbrlviewer.js"

    print('viewer path', viewer_filepath)
    args = f"--plugins={plugins} -f {output_file} --save-viewer {viewer_filepath} --viewer-url {viewer_url}"
    
```

**Comment by kwheelan** [comment]
@lucakato 

Yes, these are different files. Each session folder should have 1 `output.html` and 1 `viewer.html`.

`output.html` should be the inline xbrl file (the one that gets downloaded when you click that option on the page). `viewer.html` should be the html for the interactive viewer, which means it will include a link to the `ixbrlviewer.js` script and also include other aspects need for the sidebar, etc. All the additional code should be included under a tag `<!--BEGIN IXBRL VIEWER EXTENSIONS-->` (line 8911 for the file I looked at). 

This text: 
```
args = f"--plugins={plugins} -f {output_file} --save-viewer {viewer_filepath} --viewer-url {viewer_url}"
```
takes the converted inline xbrl (`output_file`), validates the XBRL, creates the viewer html (using the script located at the `viewer_url` location), and saves the output html at `viewer_filepath`.

**Comment by lucakato** [comment]
@kwheelan Fixed the code to generate both output.html and viewer.html. Opening the downloaded zip, it now contains output.html rather than viewer.html
