### ISSUE TITLE
[documentation] real-time process updates using ReadableStreams

### ISSUE THREAD

**Issue by lucakato** [closup/process-xbrl#86]
This is a task I was working on that I just got done. It was based on the now closed issue #25 

<h2>Goal</h2>
Add process updates, like "Uploading documents.... Converting data... Validating XBRL.... Creating viewer..."

<h2>Steps</h2>
I did some research and it looked like <b>server-sent events (SSEs)</b> would be useful for real-time updates like this, ended up using <a href="https://developer.mozilla.org/en-US/docs/Web/API/Streams_API"><b>ReadableStream of Streams API</b></a>. 

- Why not web-sockets? → seemed too complicated for this task where it was mostly server updating the client

- Why not `Fetch API`? → I tried this implementation later since Fetch API does use `ReadableStream` under the hood. However, this is not good for real-time updates where we want to incrementally process chunks of data, since `fetch` gets all the data first. What happened was the only the last message (`'conversion finishing...'`) appeared on screen.

<h2>Major changes made to code</h2>
<h3>routes.py</h3>

- Use a generator function in `upload_file()` function.
- Return a Response object with `stream_with_context(generate())` and set the content type to `'text/event-stream'`.

<h3>spinner.js</h3>

- Modified to handle the SSE stream
- It creates a FormData object from the form and sends a POST request to `'/upload'`.
- Instead of waiting for a single response, it sets up a reader to continuously read the response stream.
- The readStream function is called recursively to process each chunk of data as it arrives.
- When we see the message `Conversion finishing...` (data sent from `routes.py`) we can redirect to `/upload/complete` route.

The `readStream function` works as follows:
- It uses the `ReadableStream API` to read chunks of data from the response.
- For each chunk, it decodes the data and splits it into lines.
- It processes each line that starts with "data:", updating the UI with the message.
- It continues to call itself until the stream is complete.

<h3>Other</h3>

- Added a bunch of print statements or console logs in other functions that happen during the process that would be helpful if it were to fail.

<h2>Demo</h2>

https://github.com/user-attachments/assets/ca0f6bd6-cf5c-4c47-a1a2-568a2bc78758

<h2>Next steps</h2>

- Make it prettier → made design changes using https://www.cssscript.com/minimal-notification-popup-pure-javascript/
- Definitely would need more testing and playing around to see if it doesn't break in certain situations.

**Comment by kwheelan** [comment]
Merged in #87; closing this issue
